name: mvp_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - randomgen  # pour la génération aléatoire
  - tqdm
  - beautifulsoup4
  - pandas
  - numpy  # Manipulation efficace des données
  - matplotlib  # Visualisation des données
  - seaborn  # Pour des visualisations avancées
  - scikit-learn  # Pour la modélisation et les algorithmes ML
  - statsmodels  # Pour l'analyse statistique avancée
  - lxml  # nécessaire pour le parsing HTML avec pandas
  - sqlalchemy  # Pour interagir avec des bases de données si besoin
  - pip  # pour installer des paquets supplémentaires si besoin
  - pip:
      - html5lib  # parser HTML alternatif, utile pour certaines pages
      - urllib3  # pour le support HTTP
      - nba-api  # Spécifique pour récupérer les données NBA
      - plotly  # Pour des visualisations interactives
      - dash  # Si tu utilises Dash pour un tableau de bord
