name: mvp_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - randomgen
  - tqdm
  - beautifulsoup4
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - lxml
  - sqlalchemy
  - pip
  - scipy  # Souvent utile avec scikit-learn et numpy
  - ipykernel  # Pour les notebooks Jupyter
  - notebook  # Support des notebooks
  - ipywidgets  # Widgets interactifs pour notebooks
  - openpyxl  # Pour lire/écrire des fichiers Excel
  - xlrd  # Support pour différents formats Excel
  - pip:
      - html5lib
      - urllib3
      - nba-api
      - plotly
      - dash
      - kaleido  # Pour exporter des figures Plotly statiques